### ISSUE TITLE
what the heck is going on with npx create-react-app my-app --template redux-typescript

### ISSUE THREAD

**Issue by avida-1906** [reduxjs/redux-templates#131]
![Image](https://github.com/user-attachments/assets/e91b5154-481d-43e9-835a-131626079bf0)
when i use the command:npx create-react-app my-app --template redux-typescript to create a new project it pop up the erros like the pic show abave.

**Comment by markerikson** [comment]
React 19 is out, but the CRA templates still list a version of React Testing Library that expects React 18.  On top of that, the `npm` package manager is incredibly strict about peer dependencies, so it throws an error because of that mismatch.

That said, CRA is unmaintained at this point.  We recommend using our Vite template instead:

```bash
npx degit reduxjs/redux-templates/packages/vite-template-redux my-app
```

https://redux.js.org/introduction/installation#create-a-react-redux-app

**Comment by nickserv** [comment]
Perhaps we should mark both of the CRA templates as deprecated? React's docs don't even mention it anymore.
